# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Work/vivado_project/rom16_32/rom16_32.srcs/sources_1/ip/rom16_32/rom16_32.xci
# IP: The module: 'rom16_32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Work/vivado_project/rom16_32/rom16_32.srcs/sources_1/ip/rom16_32/rom16_32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom16_32'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Work/vivado_project/rom16_32/rom16_32.srcs/sources_1/ip/rom16_32/rom16_32.xci
# IP: The module: 'rom16_32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Work/vivado_project/rom16_32/rom16_32.srcs/sources_1/ip/rom16_32/rom16_32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom16_32'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
