# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Work/vivado_project/vga_Display_img/vga_Display_img.srcs/sources_1/ip/picture_rom/picture_rom.xci
# IP: The module: 'picture_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Work/vivado_project/vga_Display_img/vga_Display_img.srcs/sources_1/ip/picture_rom/picture_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'picture_rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Work/vivado_project/vga_Display_img/vga_Display_img.srcs/sources_1/ip/picture_rom/picture_rom.xci
# IP: The module: 'picture_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Work/vivado_project/vga_Display_img/vga_Display_img.srcs/sources_1/ip/picture_rom/picture_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'picture_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
