# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Charl/Desktop/Final/Final.srcs/sources_1/ip/origin_picture_rom/origin_picture_rom.xci
# IP: The module: 'origin_picture_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Charl/Desktop/Final/Final.srcs/sources_1/ip/origin_picture_rom/origin_picture_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'origin_picture_rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Charl/Desktop/Final/Final.srcs/sources_1/ip/origin_picture_rom/origin_picture_rom.xci
# IP: The module: 'origin_picture_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Charl/Desktop/Final/Final.srcs/sources_1/ip/origin_picture_rom/origin_picture_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'origin_picture_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
