# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Charl/Desktop/Final/Final.srcs/sources_1/ip/gray_picture_ram/gray_picture_ram.xci
# IP: The module: 'gray_picture_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Charl/Desktop/Final/Final.srcs/sources_1/ip/gray_picture_ram/gray_picture_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gray_picture_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Charl/Desktop/Final/Final.srcs/sources_1/ip/gray_picture_ram/gray_picture_ram.xci
# IP: The module: 'gray_picture_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Charl/Desktop/Final/Final.srcs/sources_1/ip/gray_picture_ram/gray_picture_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gray_picture_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
