# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Charl/Desktop/Final/Final.cache/wt [current_project]
set_property parent.project_path C:/Users/Charl/Desktop/Final/Final.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Charl/Desktop/Final/Final.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files c:/Users/Charl/Desktop/Final/origin_picture_rom.coe
add_files c:/Users/Charl/Desktop/Final/gray_picture_ram.coe
read_verilog C:/Users/Charl/Desktop/Final/Final.srcs/sources_1/new/vga_CONFIG.vh
read_verilog -library xil_defaultlib {
  C:/Users/Charl/Desktop/Final/Final.srcs/sources_1/new/clkdiv.v
  C:/Users/Charl/Desktop/Final/Final.srcs/sources_1/new/sobel_calculation.v
  C:/Users/Charl/Desktop/Final/Final.srcs/sources_1/new/vga_data.v
  C:/Users/Charl/Desktop/Final/Final.srcs/sources_1/new/vga_driver.v
  C:/Users/Charl/Desktop/Final/Final.srcs/sources_1/new/TOP.v
}
read_ip -quiet c:/Users/Charl/Desktop/Final/Final.srcs/sources_1/ip/origin_picture_rom/origin_picture_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/Charl/Desktop/Final/Final.srcs/sources_1/ip/origin_picture_rom/origin_picture_rom_ooc.xdc]

read_ip -quiet c:/Users/Charl/Desktop/Final/Final.srcs/sources_1/ip/gray_picture_ram/gray_picture_ram.xci
set_property used_in_implementation false [get_files -all c:/Users/Charl/Desktop/Final/Final.srcs/sources_1/ip/gray_picture_ram/gray_picture_ram_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Charl/Desktop/Final/Final.srcs/constrs_1/new/vga_cons.xdc
set_property used_in_implementation false [get_files C:/Users/Charl/Desktop/Final/Final.srcs/constrs_1/new/vga_cons.xdc]


synth_design -top vga_640x480_picture_top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef vga_640x480_picture_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file vga_640x480_picture_top_utilization_synth.rpt -pb vga_640x480_picture_top_utilization_synth.pb"
