# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Work/vivado_project/vga_Display_char/vga_Display_char.cache/wt [current_project]
set_property parent.project_path D:/Work/vivado_project/vga_Display_char/vga_Display_char.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Work/vivado_project/vga_Display_char/vga_Display_char.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  D:/Work/vivado_project/vga_Display_char/vga_Display_char.srcs/sources_1/new/vga_CONFIG.vh
  D:/Work/vivado_project/vga_Display_char/vga_Display_char.srcs/sources_1/new/color_CONFIG.vh
  D:/Work/vivado_project/vga_Display_char/vga_Display_char.srcs/sources_1/new/pos_CONFIG.vh
}
read_verilog -library xil_defaultlib {
  D:/Work/vivado_project/vga_Display_char/vga_Display_char.srcs/sources_1/new/clkdiv.v
  D:/Work/vivado_project/vga_Display_char/vga_Display_char.srcs/sources_1/new/vga_data.v
  D:/Work/vivado_project/vga_Display_char/vga_Display_char.srcs/sources_1/new/vga_driver.v
  D:/Work/vivado_project/vga_Display_char/vga_Display_char.srcs/sources_1/new/vga_Display_top.v
}
read_ip -quiet d:/Work/vivado_project/vga_Display_char/vga_Display_char.srcs/sources_1/ip/char_rom/char_rom.xci
set_property used_in_implementation false [get_files -all d:/Work/vivado_project/vga_Display_char/vga_Display_char.srcs/sources_1/ip/char_rom/char_rom_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Work/vivado_project/vga_Display_char/vga_Display_char.srcs/constrs_1/new/vga_Display_char.xdc
set_property used_in_implementation false [get_files D:/Work/vivado_project/vga_Display_char/vga_Display_char.srcs/constrs_1/new/vga_Display_char.xdc]


synth_design -top vga_Display_top -part xc7a100tcsg324-3


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef vga_Display_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file vga_Display_top_utilization_synth.rpt -pb vga_Display_top_utilization_synth.pb"
